<?php

namespace loeye\unit\config\general;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2020-01-16 at 15:13:23.
 */
class DeltaConfigDefinitionTest extends \loeye\unit\TestCase {

    /**
     * @var DeltaConfigDefinition
     */
    protected $object;


    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new \loeye\config\general\DeltaConfigDefinition;
    }


    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }


    /**
     * @covers loeye\config\general\DeltaConfigDefinition::getConfigTreeBuilder
     * @todo   Implement testGetConfigTreeBuilder().
     */
    public function testGetConfigTreeBuilder()
    {
        $dumper = new \Symfony\Component\Config\Definition\Dumper\YamlReferenceDumper();
        $definition = $dumper->dump($this->object);
        $this->assertStringContainsString("settings", $definition);
        $processor = new \loeye\config\Processor();
        $parser = new \Symfony\Component\Yaml\Parser();
        $configs = $parser->parseFile(PROJECT_CONFIG_DIR.DIRECTORY_SEPARATOR.'unit/general/delta.yml');
        $settins = $processor->processConfiguration($this->object, $configs);
        $this->assertIsArray($settins);
        $this->assertArrayHasKey("settings", $settins);
        $this->assertArrayHasKey("test", $settins);
    }

}
