<?php

namespace loeye\unit\config;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2020-01-08 at 14:21:14.
 */
class AppConfigDefinitionTest extends \loeye\unit\TestCase {

    /**
     * @var Definition
     */
    protected $object;


    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new \loeye\config\AppConfigDefinition;
    }


    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }


    /**
     * @covers loeye\config\Definition::getConfigTreeBuilder
     * @todo   Implement testGetConfigTreeBuilder().
     */
    public function testGetConfigTreeBuilder()
    {
        $dumper = new \Symfony\Component\Config\Definition\Dumper\YamlReferenceDumper();
        $processor = new \Symfony\Component\Config\Definition\Processor();
        $parser = new \Symfony\Component\Yaml\Parser();
        $configs = $parser->parseFile(PROJECT_UNIT_DIR.DIRECTORY_SEPARATOR.'config/unit/app/master.yml');
        $settins = $processor->processConfiguration($this->object, $configs);
        $this->assertIsArray($settins);
        $this->assertCount(1, $settins);
    }

}
