<?php

namespace loeye\unit\config;

use loeye\config\ConfigCache;
use loeye\config\ConfigResource;
use loeye\config\FileLocator;
use loeye\config\YamlFileLoader;
use loeye\unit\TestCase;
use Psr\Cache\InvalidArgumentException;
use Symfony\Component\Cache\Adapter\PhpFilesAdapter;
use Symfony\Component\Cache\Exception\CacheException;
use Symfony\Component\Filesystem\Filesystem;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2020-01-18 at 01:33:12.
 */
class ConfigCacheTest extends TestCase {

    /**
     * @var ConfigCache
     */
    protected $object;

    protected $cacheDir;

    protected $namespace;

    protected $path;


    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     * @throws CacheException
     */
    protected function setUp()
    {
        $this->path = PROJECT_CONFIG_DIR;
        $this->cacheDir = RUNTIME_CACHE_DIR;
        $fileSystem = new Filesystem();
        if ($fileSystem->exists($this->cacheDir)){
            $fileSystem->remove($this->cacheDir);
        }

        $this->namespace = 'unit.app';
        $this->object = new ConfigCache($this->path, $this->cacheDir, $this->namespace);
    }


    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        $fileSystem = new Filesystem();
        if ($fileSystem->exists($this->cacheDir)){
            $fileSystem->remove($this->cacheDir);
        }
    }


    /**
     * @covers \loeye\config\ConfigCache::nsToPattern
     */
    public function testNsToPattern()
    {
        $this->assertEquals(DIRECTORY_SEPARATOR.'unit/app', $this->object->nsToPattern());
    }


    /**
     * @covers \loeye\config\ConfigCache::getMetaFile
     */
    public function testGetMetaFile()
    {
        $actual = $this->object->getMetaFile();
        $expected = PROJECT_UNIT_RUNTIME_DIR .DIRECTORY_SEPARATOR .'cache'. DIRECTORY_SEPARATOR.$this->namespace
            .DIRECTORY_SEPARATOR. md5(serialize([$this->path, DIRECTORY_SEPARATOR.'unit/app'])).'.meta';
        $this->assertEquals($expected, $actual);
    }


    /**
     * @covers \loeye\config\ConfigCache::getResourceByMetaFile
     */
    public function testGetResourceByMetaFile()
    {
        $this->assertInstanceOf(ConfigResource::class, $this->object->getResourceByMetaFile());
    }


    /**
     * @covers \loeye\config\ConfigCache::isFresh
     */
    public function testIsFresh()
    {
        $this->assertTrue($this->object->isFresh());
    }


    /**
     * @covers \loeye\config\ConfigCache::cacheAdapter
     */
    public function testCacheAdapter()
    {
        $this->assertInstanceOf(PhpFilesAdapter::class, $this->object->cacheAdapter());
    }


    /**
     * @covers \loeye\config\ConfigCache::write
     * @throws InvalidArgumentException
     */
    public function testWriteList()
    {
        $locator = new FileLocator(PROJECT_UNIT_DIR . DIRECTORY_SEPARATOR . 'conf');
        $ymlLoader = new YamlFileLoader($locator);
        $ymlLoader->setCurrentDir('unit/app');
//        $configes = $ymlLoader->import('*.yml');
        $contents = ['master' => ['aaa'], 'delta' => ['test' => ['vvv']]];
        $this->object->write($contents);
        $actual = $this->object->cacheAdapter()->getItem('master')->get();
        $this->assertEquals($contents['master'], $actual);
    }

}
