<?php

namespace loeye\unit\config;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2020-01-18 at 12:13:20.
 */
class ConfigurationLoaderTest extends \loeye\unit\TestCase {

    /**
     * @var ConfigurationLoader
     */
    protected $object;


    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $directory = PROJECT_UNIT_DIR .DIRECTORY_SEPARATOR .'config';
        $namespace = 'unit.app';
        $definition = new \loeye\config\app\ConfigDefinition();
        $this->object = new \loeye\config\ConfigurationLoader($directory, $namespace, $definition);
    }


    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }


    /**
     * @covers loeye\config\ConfigurationLoader::getDirectory
     * @todo   Implement testGetDirectory().
     */
    public function testGetDirectory()
    {
        $actual = $this->object->getDirectory();
        $expected = PROJECT_UNIT_DIR .DIRECTORY_SEPARATOR .'config';
        $this->assertEquals($expected, $actual);
    }


    /**
     * @covers loeye\config\ConfigurationLoader::load
     * @todo   Implement testLoad().
     */
    public function testLoad()
    {
        $actual = $this->object->load();
        $this->assertIsArray($actual);
        $this->assertArrayHasKey('constants', $actual);
        $this->assertArrayHasKey('application', $actual);
    }


    /**
     * @covers loeye\config\ConfigurationLoader::getCache
     * @todo   Implement testGetCache().
     */
    public function testGetCache()
    {
        $actual = $this->object->getCache('master');
        $this->assertIsArray($actual);
        $this->assertArrayHasKey('constants', $actual);
        $this->assertArrayHasKey('application', $actual);
    }

}
