<?php

namespace loeye\unit\config;

use loeye\config\FileLocator;
use loeye\unit\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2020-01-07 at 15:28:59.
 */
class FileLocatorTest extends TestCase {

    /**
     * @var FileLocator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $paths = PROJECT_CONFIG_DIR;
        $this->object = new FileLocator($paths);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @cover FileLocator::locate
     * @todo   Implement testLocate().
     */
    public function testLocate() {
        $this->assertEquals(realpath(PROJECT_UNIT_DIR.DIRECTORY_SEPARATOR.'conf/unit/app/master.yml'), $this->object->locate('master.yml', 'unit/app', true));
    }

}
