<?php

/**
 * GenerateServer.php
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"),
 * see LICENSE for more details: http://www.apache.org/licenses/LICENSE-2.0.
 * 
 * @author  Zhang Yi <loeyae@gmail.com>
 * @version SVN: $Id: Zhang Yi $
 */

namespace loeye\commands;

use loeye\console\Command;
use \Symfony\Component\Console\{
    Input\InputInterface,
    Output\OutputInterface
};

/**
 * GenerateServer
 *
 * @author   Zhang Yi <loeyae@gmail.com>
 */
class GenerateServer extends Command {

    use \loeye\console\helper\EntityGeneratorTraite;

    protected $args   = [
        ['property', 'required' => true, 'help' => 'The application property name.']
    ];
    protected $params = [
        ['db-id', 'd', 'required' => false, 'help' => 'database setting id', 'default' => 'default'],
        ['filter', 'f', 'required' => false, 'help' => 'filter', 'default' => null],
        ['force', null, 'required' => false, 'help' => 'force update file', 'default' => false],
    ];
    protected $name             = 'loeye:generate-server';
    protected static $_template = '<?php

namespace <namespace>;

/**
 * <className>
 *
 * This class was generated by the loeye2. Add your own custom
 * server methods below.
 */
class <className> extends <serverName>
{
    protected $entityClass = <entityClass>;
}
';


    /**
     * generateFile
     * 
     * @param \Symfony\Component\Console\Style\SymfonyStyle $ui
     * @param \Doctrine\Persistence\Mapping\ClassMetadata   $metadata
     * @param string                                        $namespace
     * @param string                                        $destPath
     */
    protected function generateFile(\Symfony\Component\Console\Style\SymfonyStyle $ui, \Doctrine\Persistence\Mapping\ClassMetadata $metadata, $namespace, $destPath, $force)
    {
        $className     = $this->getClassNmae($metadata->reflClass->name);
        $entityClass   = $this->getEntityClass($metadata->reflClass->name);
        $fullClassName = $namespace . '\\' . $className;
        $ui->text(sprintf('Processing Server "<info>%s</info>"', $fullClassName));
        $this->writeServerClass($namespace, $className, $entityClass, $destPath, $force);
    }


    /**
     * 
     * @param InputInterface $input
     * 
     * @return string
     */
    protected function getDestPath(InputInterface $input)
    {
        return PROJECT_MODELS_DIR . D_S . 'server' . D_S . $input->getArgument('property');
    }


    /**
     * getEntityClass
     * 
     * @param string $className
     * @return type
     */
    protected function getEntityClass($className)
    {
        return '\\' . $className . '::class';
    }


    /**
     * getClassNmae
     * 
     * @param string $fullClassName
     * @return string
     */
    protected function getClassNmae($fullClassName)
    {
        return substr($fullClassName, strrpos($fullClassName, '\\') + 1) . 'Server';
    }


    /**
     * generateServerClass
     * 
     * @param string $namespace
     * @param string $className
     * @param string $entityClass
     * @return string
     */
    protected function generateServerClass($namespace, $className, $entityClass)
    {
        $variables = [
            '<namespace>'   => $namespace,
            '<serverName>'  => '\\loeye\\database\\Server',
            '<className>'   => $className,
            '<entityClass>' => $entityClass,
        ];

        return str_replace(array_keys($variables), array_values($variables), self::$_template);
    }


    /**
     * writeServerClass
     * 
     * @param string  $namespace
     * @param string  $className
     * @prara String  $entityClass
     * @param string  $outputDirectory
     * @param boolean $force
     */
    public function writeServerClass($namespace, $className, $entityClass, $outputDirectory, $force = false)
    {
        $code = $this->generateServerClass($namespace, $className, $entityClass);

        $this->writeFile($outputDirectory, $className, $code, $force);
    }

}
