<?php

namespace loeye\unit\config\router;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2020-01-16 at 09:49:32.
 */
class ConfigDefinitionTest extends \loeye\unit\TestCase
{

    /**
     * @var ConfigDefinition
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new \loeye\config\router\ConfigDefinition;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers loeye\config\router\ConfigDefinition::getConfigTreeBuilder
     * @todo   Implement testGetConfigTreeBuilder().
     */
    public function testGetConfigTreeBuilder()
    {
        $dumper = new \Symfony\Component\Config\Definition\Dumper\YamlReferenceDumper();
        $definition = $dumper->dump($this->object);
        $this->assertStringContainsString("settings", $definition);
        $this->assertStringContainsString("routes", $definition);
        $processor = new \loeye\config\Processor();
        $parser = new \Symfony\Component\Yaml\Parser();
        $configs = $parser->parseFile(PROJECT_UNIT_DIR.DIRECTORY_SEPARATOR.'config/unit/router/master.yml');
        $settins = $processor->processConfiguration($this->object, $configs);
        $this->assertIsArray($settins);
        $this->assertArrayHasKey("settings", $settins);
        $this->assertArrayHasKey("routes", $settins);
    }

}
