<?php

namespace loeye\unit\config\cache;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2020-01-15 at 09:28:43.
 */
class ConfigDefinitionTest extends \loeye\unit\TestCase
{

    /**
     * @var ConfigDefinition
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new \loeye\config\cache\ConfigDefinition;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers loeye\config\cache\ConfigDefinition::getConfigTreeBuilder
     * @todo   Implement testGetConfigTreeBuilder().
     */
    public function testGetConfigTreeBuilderBase()
    {
        $dumper = new \Symfony\Component\Config\Definition\Dumper\YamlReferenceDumper();
        $definition = $dumper->dump($this->object);
        $this->assertStringContainsString("settings", $definition);
        $this->assertStringContainsString("apc", $definition);
        $this->assertStringContainsString("memcached", $definition);
//        $this->assertStringContainsString("file", $definition);
        $this->assertStringContainsString("0", $dumper->dumpAtPath($this->object, "settings"));
    }

    /**
     * @covers loeye\config\cache\ConfigDefinition::getConfigTreeBuilder
     * @todo   Implement testGetConfigTreeBuilder().
     */
    public function testGetConfigTreeBuilderApc()
    {
        $processor = new \loeye\config\Processor();
        $parser = new \Symfony\Component\Yaml\Parser();
        $configs = $parser->parseFile(PROJECT_CONFIG_DIR.DIRECTORY_SEPARATOR.'unit/cache/apc.yml');
        $settins = $processor->processConfiguration($this->object, $configs);
        $this->assertIsArray($settins);
        $this->assertArrayHasKey("settings", $settins);
        $this->assertArrayHasKey("apc", $settins);
    }

    /**
     * @covers loeye\config\cache\ConfigDefinition::getConfigTreeBuilder
     * @todo   Implement testGetConfigTreeBuilder().
     */
    public function testGetConfigTreeBuilderMecached()
    {
        $processor = new \loeye\config\Processor();
        $parser = new \Symfony\Component\Yaml\Parser();
        $configs = $parser->parseFile(PROJECT_CONFIG_DIR.DIRECTORY_SEPARATOR.'unit/cache/mem.yml');
        $settins = $processor->processConfiguration($this->object, $configs);
        $this->assertIsArray($settins);
        $this->assertArrayHasKey("settings", $settins);
        $this->assertArrayHasKey("memcached", $settins);
    }

    /**
     * @covers loeye\config\cache\ConfigDefinition::getConfigTreeBuilder
     * @todo   Implement testGetConfigTreeBuilder().
     */
    public function testGetConfigTreeBuilderRedis()
    {
        $processor = new \loeye\config\Processor();
        $parser = new \Symfony\Component\Yaml\Parser();
        $configs = $parser->parseFile(PROJECT_CONFIG_DIR.DIRECTORY_SEPARATOR.'unit/cache/redis.yml');
        $settins = $processor->processConfiguration($this->object, $configs);
        $this->assertIsArray($settins);
        $this->assertArrayHasKey("settings", $settins);
        $this->assertArrayHasKey("redis", $settins);
    }

    /**
     * @covers loeye\config\cache\ConfigDefinition::getConfigTreeBuilder
     * @todo   Implement testGetConfigTreeBuilder().
     */
    public function testGetConfigTreeBuilderPfile()
    {
        $processor = new \loeye\config\Processor();
        $parser = new \Symfony\Component\Yaml\Parser();
        $configs = $parser->parseFile(PROJECT_CONFIG_DIR.DIRECTORY_SEPARATOR.'unit/cache/pfile.yml');
        $settins = $processor->processConfiguration($this->object, $configs);
        $this->assertIsArray($settins);
        $this->assertArrayHasKey("settings", $settins);
        $this->assertArrayHasKey("pfile", $settins);
    }

    /**
     * @covers loeye\config\cache\ConfigDefinition::getConfigTreeBuilder
     * @todo   Implement testGetConfigTreeBuilder().
     */
    public function testGetConfigTreeBuilderFile()
    {
        $processor = new \loeye\config\Processor();
        $parser = new \Symfony\Component\Yaml\Parser();
        $configs = $parser->parseFile(PROJECT_CONFIG_DIR.DIRECTORY_SEPARATOR.'unit/cache/file.yml');
        $settins = $processor->processConfiguration($this->object, $configs);
        $this->assertIsArray($settins);
        $this->assertArrayHasKey("settings", $settins);
        $this->assertArrayHasKey("file", $settins);
    }

}
