<?php

namespace loeye\unit\config\app;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2020-01-08 at 14:21:14.
 */
class ConfigDefinitionTest extends \loeye\unit\TestCase {

    /**
     * @var Definition
     */
    protected $object;


    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new \loeye\config\app\ConfigDefinition;
    }


    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }


    /**
     * @covers loeye\config\Definition::getConfigTreeBuilder
     * @todo   Implement testGetConfigTreeBuilder().
     */
    public function testGetConfigTreeBuilder()
    {
        $dumper = new \Symfony\Component\Config\Definition\Dumper\YamlReferenceDumper();
        $definition = $dumper->dump($this->object);
        $this->assertStringContainsString("settings", $definition);
        $this->assertStringContainsString("constants", $definition);
        $this->assertStringContainsString("application", $definition);
        $this->assertStringContainsString("configuration", $definition);
        $this->assertStringContainsString("0", $dumper->dumpAtPath($this->object, "settings"));
        $processor = new \loeye\config\Processor();
        $parser = new \Symfony\Component\Yaml\Parser();
        $configs = $parser->parseFile(PROJECT_UNIT_DIR.DIRECTORY_SEPARATOR.'config/unit/app/master.yml');
        $settins = $processor->processConfiguration($this->object, $configs);
        $this->assertIsArray($settins);
        $this->assertArrayHasKey("settings", $settins);
    }

    public function testGetConfigTreeBuilderTest()
    {
        $processor = new \loeye\config\Processor();
        $parser = new \Symfony\Component\Yaml\Parser();
        $configs = $parser->parseFile(PROJECT_UNIT_DIR.DIRECTORY_SEPARATOR.'config/unit/app/test.yml');
        $settins = $processor->processConfiguration($this->object, $configs);
        $this->assertIsArray($settins);
        $this->assertArrayHasKey("settings", $settins);
    }

    public function testGetConfigTreeBuilderMulti()
    {
        $processor = new \loeye\config\Processor();
        $parser = new \Symfony\Component\Yaml\Parser();
        $configs = $parser->parseFile(PROJECT_UNIT_DIR.DIRECTORY_SEPARATOR.'config/unit/app/multi.yml');
        $settins = $processor->processConfiguration($this->object, $configs);
        $this->assertIsArray($settins);
        $this->assertArrayHasKey("settings", $settins);
    }

}
