<?php

namespace loeye\unit\config\app;

use loeye\config\app\DeltaDefinition;
use loeye\config\Processor;
use loeye\unit\TestCase;
use Symfony\Component\Config\Definition\Dumper\YamlReferenceDumper;
use Symfony\Component\Yaml\Parser;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2020-01-19 at 09:32:09.
 */
class DeltaDefinitionTest extends TestCase
{

    /**
     * @var DeltaDefinition
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new DeltaDefinition;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers \loeye\config\app\DeltaDefinition::getConfigTreeBuilder
     */
    public function testGetConfigTreeBuilder()
    {
        $dumper = new YamlReferenceDumper();
        $definition = $dumper->dump($this->object);
        $this->assertStringContainsString('settings', $definition);
        $this->assertStringContainsString('profile', $definition);
        $processor = new Processor();
        $parser = new Parser();
        $configs = $parser->parseFile(PROJECT_CONFIG_DIR.DIRECTORY_SEPARATOR.'unit/app/dev.yml');
        $settings = $processor->processConfiguration($this->object, $configs);
        $this->assertIsArray($settings);
        $this->assertArrayHasKey('settings', $settings);
        $this->assertArrayHasKey('constants', $settings);
    }

}
