<?php

namespace loeye\unit\config\database;

use loeye\config\database\ConfigDefinition;
use loeye\config\Processor;
use loeye\unit\TestCase;
use Symfony\Component\Config\Definition\Dumper\YamlReferenceDumper;
use Symfony\Component\Yaml\Parser;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2020-01-15 at 12:38:17.
 */
class ConfigDefinitionTest extends TestCase {

    /**
     * @var ConfigDefinition
     */
    protected $object;


    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ConfigDefinition;
    }


    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }


    /**
     * @covers \loeye\config\database\ConfigDefinition::getConfigTreeBuilder
     */
    public function testGetConfigTreeBuilder()
    {
        $dumper     = new YamlReferenceDumper();
        $definition = $dumper->dump($this->object);
        $this->assertStringContainsString('settings', $definition);
        $this->assertStringContainsString('driver', $definition);
        $this->assertStringContainsString('0', $dumper->dumpAtPath($this->object, 'settings'));
        $processor  = new Processor();
        $parser     = new Parser();
        $configs    = $parser->parseFile(PROJECT_CONFIG_DIR . DIRECTORY_SEPARATOR . 'unit/database/master.yml');
        $settings    = $processor->processConfiguration($this->object, $configs);
        $this->assertIsArray($settings);
        $this->assertArrayHasKey('settings', $settings);
        $this->assertArrayHasKey('default', $settings);
    }

}
